### ISSUE TITLE
OpenSSL error that brings down the connection with no attempt to reconnect

### ISSUE THREAD

**Issue by jomag** [horazont/aioxmpp#116]
I have the same software running on two locations. The hardware is identical (Raspberry Pi), and so is the software.

The first location runs with no problems. It has a stable ethernet connection.

The second location has a bit flaky wifi connection and the connection goes down every hour or so. It seems to happen more often when there is a lot of communication going on, but it can happen at every time. One more thing that is different is that the root filesystem is read-only.

This is what I've captured from the log:

```
[3286.014] ERR:  [asyncio] Fatal write error on STARTTLS transport
protocol: <aioxmpp.protocol.XMLStream object at 0xb41d0ad0>
transport: <aioopenssl.STARTTLSTransport object at 0xb41d0c10>Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/aioopenssl/__init__.py", line 478, in _write_ready
    nsent = self._sock.send(bytes(self._buffer))
  File "/usr/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1254, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1172, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3.5/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_write_pending', 'bad write retry')]

[3286.097] INFO: [ra.xmpp.gateway] XMPP stream destroyed
[3286.153] ERR:  [aioxmpp.StanzaStream] broker task failedTraceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/aioxmpp/stream.py", line 813, in _done_handler
    task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/site-packages/aioxmpp/stream.py", line 1844, in _run
    self._process_outgoing(xmlstream, active_fut.result())
  File "/usr/lib/python3.5/site-packages/aioxmpp/stream.py", line 1196, in _process_outgoing
    self._send_stanza(xmlstream, token)
  File "/usr/lib/python3.5/site-packages/aioxmpp/stream.py", line 1181, in _send_stanza
    xmlstream.send_xso(stanza_obj)
  File "/usr/lib/python3.5/site-packages/aioxmpp/protocol.py", line 641, in send_xso
    self._require_connection()
  File "/usr/lib/python3.5/site-packages/aioxmpp/protocol.py", line 374, in _require_connection
    raise self._exception
  File "/usr/lib/python3.5/site-packages/aioopenssl/__init__.py", line 478, in _write_ready
    nsent = self._sock.send(bytes(self._buffer))
  File "/usr/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1254, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1172, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3.5/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_write_pending', 'bad write retry')]

[3286.236] ERR:  [aioxmpp.node.PresenceManagedClient] stream failed: [('SSL routines', 'ssl3_write_pending', 'bad write retry')]
[3286.270] INFO: [aioxmpp.node.PresenceManagedClient] stopping stream
[3286.284] ERR:  [aioxmpp.node.PresenceManagedClient] main failedTraceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/aioxmpp/node.py", line 730, in _on_main_done
    task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/site-packages/aioxmpp/node.py", line 888, in _main
    yield from self._main_impl()
  File "/usr/lib/python3.5/site-packages/aioxmpp/node.py", line 864, in _main_impl
    raise exc
  File "/usr/lib/python3.5/site-packages/aioxmpp/stream.py", line 813, in _done_handler
    task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/site-packages/aioxmpp/stream.py", line 1844, in _run
    self._process_outgoing(xmlstream, active_fut.result())
  File "/usr/lib/python3.5/site-packages/aioxmpp/stream.py", line 1196, in _process_outgoing
    self._send_stanza(xmlstream, token)
  File "/usr/lib/python3.5/site-packages/aioxmpp/stream.py", line 1181, in _send_stanza
    xmlstream.send_xso(stanza_obj)
  File "/usr/lib/python3.5/site-packages/aioxmpp/protocol.py", line 641, in send_xso
    self._require_connection()
  File "/usr/lib/python3.5/site-packages/aioxmpp/protocol.py", line 374, in _require_connection
    raise self._exception
  File "/usr/lib/python3.5/site-packages/aioopenssl/__init__.py", line 478, in _write_ready
    nsent = self._sock.send(bytes(self._buffer))
  File "/usr/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1254, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1172, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3.5/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_write_pending', 'bad write retry')]
```

It's unfortunate that this happens, but the worst thing is that it does not attempt to reconnect when this happens. I'm afraid my SSL-fu is not strong enough to understand what's going on.

**Comment by horazont** [comment]
First of all, as a workaround, on v0.8, it should be possible to change line 898 of node.py to:
```python
                except (OSError, dns.resolver.NoNameservers, OpenSSL.SSL.Error) as exc:
```

Secondly, the issue is twofold: (a) this error should not prevent reconnection and (b) this specific error should not happen. (a) is addressed with the workaround above.

(b) is more tricky. This is a bug in aioopenssl. According to a [stackoverflow answer](https://stackoverflow.com/questions/2997218/why-am-i-getting-error1409f07fssl-routinesssl3-write-pending-bad-write-retr):

> For example, when SSL_write(ssl, ptr, size) with ptr = 0xABCDEFGH, size = 4096 fails with SSL_ERROR_WANT_READ or SSL_ERROR_WANT_WRITE, when retrying the SSL_write call, the parameters ptr and size should be same. It is not equivalent if ptr is another pointer pointing to a copy of the same contents as in the original call. 

This is not enforced in aioopenssl, and this also shows why it happens more often with more traffic: the more traffic, the more likely it is that after an incomplete write (for example, due to a laggy TCP connection caused by an unstable WiFi link), more data is appended to the buffer, changing size and/or ptr.

I will look into solutions for that.

**Comment by horazont** [comment]
I put the suggested workaround into the release (see 97b3472). Further discussion of the SSL issue itself shall happen in horazont/aioopenssl#4.
