### ISSUE TITLE
Using simple connector without SSL or TLS

### ISSUE THREAD

**Issue by vit1251** [horazont/aioxmpp#153]
Hello,

Could you explain please how to make connection over raw TCP/IP connection or substitute c onnection on my own implementation?

Thanks.

**Comment by horazont** [comment]
Hey,

Thanks for your question.

This is intentionally not trivial and will disable plaintext authentication. Please make sure that you really have to disable STARTTLS / XMPPS support and there is no other way (such as key pinning, which is supported by aioxmpp).

*Iff* you absolutely **have** to disable the transport security, you can do that today with:

```python
security_layer = aioxmpp.make_security_layer(…)._replace(tls_required=False)
client = aioxmpp.Client(jid, security_layer)
```

(The ``_replace`` method is part of the namedtuple API.)

The ``…`` represent the usual arguments to the make_security_layer method. See the documentation of [SecurityLayer](https://docs.zombofant.net/aioxmpp/devel/api/public/security_layer.html#aioxmpp.security_layer.SecurityLayer) and [make_security_layer](https://docs.zombofant.net/aioxmpp/devel/api/public/security_layer.html#aioxmpp.security_layer.make), as well as the [quick start](https://docs.zombofant.net/aioxmpp/devel/user-guide/quickstart.html#connect-to-an-xmpp-server-with-jid-and-password).

If you want to use an existing TCP connection, you’ll have to subclass ``aioxmpp.connector.BaseConnector``, which is not really part of the public API. I’d invite you to discuss your use-case to see if we can find a proper solution in that case.

Good luck.

**Comment by vit1251** [comment]
Hello,
I does not want to use hack make_security_layer properties and select second way.
But when I create inheritor on BaseCconnector and provide 

```
    client = Client(
        local_jid=jid,
        security_layer=None,
        override_peer=( host, port, connector ),
    )
```

I receive a wery large exception:

```
Traceback (most recent call last):
  File "./01_aioxmpp_example.py3", line 91, in <module>
    main()
  File "./01_aioxmpp_example.py3", line 85, in main
    loop.run_until_complete(start_speak())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "./01_aioxmpp_example.py3", line 74, in start_speak
    async with client.connected() as stream:
  File "/usr/local/lib/python3.5/dist-packages/aioxmpp/node.py", line 1403, in __aenter__
    yield from conn_future
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/aioxmpp/node.py", line 761, in _on_main_done
    task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/aioxmpp/node.py", line 921, in _main
    yield from self._main_impl()
  File "/usr/local/lib/python3.5/dist-packages/aioxmpp/node.py", line 883, in _main_impl
    logger=self.logger)
  File "/usr/local/lib/python3.5/dist-packages/aioxmpp/node.py", line 358, in connect_xmlstream
    jid, metadata, negotiation_timeout, loop, logger,
  File "/usr/local/lib/python3.5/dist-packages/aioxmpp/node.py", line 216, in _try_options
    for host, port, conn in options:
ValueError: too many values to unpack (expected 3)
```
Could you help me with this issue? I should make connect async? Where I can see BaseConnector example implementation?

**Comment by horazont** [comment]
Try passing ``override_peer=[(host, port, connector)]`` to the Client constructor; ``override_peer`` is supposed to be a sequence of tuples, not a tuple.

**Comment by vit1251** [comment]
Sequence is resolve my problem. Thanks.
Let's try to implement BaseConnector now.

**Comment by horazont** [comment]
@vit1251 I’d be happy to accept a PR including that subclass, even though it won’t be used automatically. I can see use-cases for example for controlled local networks etc.

**Comment by horazont** [comment]
Closing this for now. If you have further questions w.r.t. this topic, feel free to post here. If you have other questions, drop by the MUC (see the README) or the mailing list or open another issue. If you want to submit your code, feel free to open a PR.
