### ISSUE TITLE
Add xmpp_block to examples

### ISSUE THREAD

**Issue by mcepl** [horazont/aioxmpp#21]
https://gitlab.com/mcepl/jabberd_utils/blob/master/xmpp_block

It is a script blocking all JIDs (full or partial) added on the command line to the [XEP-0191](https://xmpp.org/extensions/xep-0191.html) blocking list. Could be useful for combating current wave of Jabber spam.

**Comment by horazont** [comment]
I included the example by re-structuring it a bit. It is in ``examples/xep191_block.py``. Please test if you can, because the servers I use do not support that feature currently. The CLI has changed slightly, but --help and the examples readme should show you the way around.

It also requires Python 3.5+ to run.

**Comment by mcepl** [comment]
Unfortunately, not python3.5 around, so I just have to trust you (and note, that it seems sad you require just the very very latest release of Python).

**Comment by horazont** [comment]
@mcepl Good point, aioxmpp itself is still python 3.4-compatible.

I have pushed a few commits to master which backport the examples to Python 3.4, and if there will be a 0.7.2 release, it will contain the backported examples.

Please test the block_jid example.

**Comment by mcepl** [comment]
@horazont what do you think about this? That makes the script directly useable.

**Comment by mcepl** [comment]
```
matej@mitmanek: ~$ block_jid --add jabber.me
Traceback (most recent call last):
  File "/home/matej/.local/bin/block_jid", line 192, in <module>
    exec_example(BlockJID())
  File "/home/matej/archiv/knihovna/repos/aioxmpp/examples/framework.py", line 168, in exec_example
    loop.run_until_complete(example.run_example())
  File "/usr/lib64/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib64/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/home/matej/archiv/knihovna/repos/aioxmpp/examples/framework.py", line 155, in run_example
    yield from self.run_simple_example()
  File "/home/matej/.local/bin/block_jid", line 169, in run_simple_example
    iq
  File "/home/matej/archiv/knihovna/repos/aioxmpp/aioxmpp/stream.py", line 2129, in send_iq_and_wait_for_reply
    reply = yield from fut
  File "/usr/lib64/python3.4/asyncio/futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib64/python3.4/asyncio/tasks.py", line 287, in _wakeup
    value = future.result()
  File "/usr/lib64/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
aioxmpp.errors.XMPPModifyError: {urn:ietf:params:xml:ns:xmpp-stanzas}bad-request
matej@mitmanek: ~$
```
What's the problem?

**Comment by horazont** [comment]
I made a mistake when copying the implementation from ``xmpp_block``. Fixed in devel.

**Comment by mcepl** [comment]
Yes, the last version works. Thank you.
