### ISSUE TITLE
OpenSSL.SSL.Error

### ISSUE THREAD

**Issue by spice0xff** [horazont/aioxmpp#282]
Hi!
I try this code:
```
class FCMPayload(aioxmpp.xso.XSO):
    TAG = ("google:mobile:data", "gcm")
    text = aioxmpp.xso.Text(default=None)


async def main(jid, password, recipient):
    aioxmpp.stanza.Message.fcm_payload = aioxmpp.xso.Child([FCMPayload])

    client = aioxmpp.node.PresenceManagedClient(
        aioxmpp.structs.JID.fromstr(jid),
        aioxmpp.security_layer.tls_with_password_based_authentication(password),
        override_peer=[(FCM_SERVER_URL, FCM_SERVER_PORT, aioxmpp.connector.XMPPOverTLSConnector())],
    )

    payload = FCMPayload()
    payload.text = json.dumps({
        "message_id": str(uuid.uuid4()),
        "to": recipient,
        "data": {
            "test": "test"
        }
    })

    async with aioxmpp.node.UseConnected(client, timeout=datetime.timedelta(seconds=30)) as stream:
        msg = aioxmpp.stanza.Message(type_="normal", id_="")
        msg.fcm_payload = payload
        await stream.send_and_wait_for_sent(msg)


asyncio.get_event_loop().run_until_complete(main(FCM_JID, FCM_API_KEY, RECIPIENT))
```

And get follow error:
```
certificate verification failed (by OpenSSL)
Fatal error on tls handshake
protocol: <aioxmpp.protocol.XMLStream object at 0x0000000004AAE978>
transport: <aioopenssl.STARTTLSTransport object at 0x0000000004AAEC50>
Traceback (most recent call last):
  File "C:\dev\PycharmProjects\aioxmpp_test_py_3.7.2\lib\site-packages\aioopenssl\__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "C:\dev\PycharmProjects\aioxmpp_test_py_3.7.2\lib\site-packages\OpenSSL\SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\dev\PycharmProjects\aioxmpp_test_py_3.7.2\lib\site-packages\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "C:\dev\PycharmProjects\aioxmpp_test_py_3.7.2\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "C:\dev\PycharmProjects\aioxmpp_test_py_3.7.2\lib\site-packages\aioopenssl\__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "C:\dev\PycharmProjects\aioxmpp_test_py_3.7.2\lib\site-packages\OpenSSL\SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\dev\PycharmProjects\aioxmpp_test_py_3.7.2\lib\site-packages\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "C:\dev\PycharmProjects\aioxmpp_test_py_3.7.2\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bin\Python37\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\dev\PycharmProjects\aioxmpp_test_py_3.7.2\lib\site-packages\aioopenssl\__init__.py", line 346, in _tls_do_handshake
    self._waiter.set_exception(exc)
asyncio.base_futures.InvalidStateError: invalid state
connection failed: _force_close() called
```

Envairoment:
windows 7 and debian 8
Python 3.7.2
aioxmpp 0.10.3

**Comment by horazont** [comment]
can you please try, in your shell:
```bash
openssl s_client -connect FCM_SERVER_URL:FCM_SERVER_PORT < /dev/null | grep -i verif
```
(of course with the proper replacements for the variables above) and paste the output?

**Comment by Fatal1ty** [comment]
> can you please try, in your shell:
> 
> ```shell
> openssl s_client -connect FCM_SERVER_URL:FCM_SERVER_PORT < /dev/null | grep -i verif
> ```
> 
> (of course with the proper replacements for the variables above) and paste the output?

Hello! This problem comes from my `aiofcm` library. I have the same problem.
```
depth=2 OU = GlobalSign Root CA - R2, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = US, O = Google Trust Services, CN = Google Internet Authority G3
verify return:1
depth=0 C = US, ST = California, L = Mountain View, O = Google LLC, CN = *.googleapis.com
verify return:1
poll error    Verify return code: 0 (ok)
```

My environment: macOS 10.14.3 / Python 3.7.0 / aioxmpp 0.10.13 / aioopenssl 0.4.0 / pyOpenSSL 19.0.0.
```
LibreSSL 2.6.5
built on: date not available
platform: information not available
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) blowfish(idx)
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"
```

**Comment by Fatal1ty** [comment]
Btw, The server we connecting to is fcm-xmpp.googleapis.com:5235

**Comment by Fatal1ty** [comment]
Btw, the server we connecting to is fcm-xmpp.googleapis.com:5235

**Comment by Fatal1ty** [comment]
Btw, the server we're connecting to is fcm-xmpp.googleapis.com:5235

**Comment by Fatal1ty** [comment]
The extended log with debug information. I hope it could help.
```
DEBUG:aiofcm:Message 38ac5510-f17f-4679-8da3-1d35e78fd4bb: waiting for connection
DEBUG:aioxmpp.callbacks:connecting <bound method SimpleMessageDispatcher._feed of <aioxmpp.dispatcher.SimpleMessageDispatcher object at 0x10ebab240>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.callbacks:connecting <bound method SimplePresenceDispatcher._feed of <aioxmpp.dispatcher.SimplePresenceDispatcher object at 0x10ebab320>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.node.Client.on_stream_established:connecting <function FCMXMPPConnection.connect.<locals>.<lambda> at 0x10ea65598> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.node.Client.on_stream_destroyed:connecting <bound method FCMXMPPConnection._on_stream_destroyed of <aiofcm.connection.FCMXMPPConnection object at 0x10e023ba8>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.callbacks:connecting <bound method Client._stream_failure of <aioxmpp.node.Client object at 0x10d075da0>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.callbacks:connecting <bound method Client._stream_destroyed of <aioxmpp.node.Client object at 0x10d075da0>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.node.Client:domain gcm.googleapis.com: trying to connect to 'fcm-xmpp.googleapis.com':5235 using <aioxmpp.connector.XMPPOverTLSConnector object at 0x10d075400>
DEBUG:aioxmpp.callbacks:connecting <bound method XMLStream._deadtime_hard_limit_triggered of <aioxmpp.protocol.XMLStream object at 0x10ebab5f8>> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioxmpp.callbacks:connecting <aioxmpp.callbacks.AdHocSignal object at 0x10ebab710> with mode <bound method AdHocSignal.STRONG of <class 'aioxmpp.callbacks.AdHocSignal'>>
DEBUG:aioopenssl.trace.fd=14:_initiate_tls called
DEBUG:aioopenssl.trace.fd=14:_tls_do_handshake called
DEBUG:aioopenssl.trace.fd=14:registering reader for _tls_do_handshake
DEBUG:aioopenssl.trace.fd=14:_tls_do_handshake called
INFO:aioxmpp.security_layer:verifying certificate (preverify=0)
WARNING:aioxmpp.security_layer:certificate verification failed (by OpenSSL)
DEBUG:aioopenssl.trace.fd=14:clearing readers/writers
ERROR:asyncio:Fatal error on tls handshake
protocol: <aioxmpp.protocol.XMLStream object at 0x10ebab5f8>
transport: <aioopenssl.STARTTLSTransport object at 0x10ebab748>
Traceback (most recent call last):
  File "/Users/tikhonov_a/.pyenv/versions/aiofcm/lib/python3.7/site-packages/aioopenssl/__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "/Users/tikhonov_a/.pyenv/versions/aiofcm/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/tikhonov_a/.pyenv/versions/aiofcm/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/Users/tikhonov_a/.pyenv/versions/aiofcm/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
DEBUG:aioopenssl.trace.fd=14:_force_close called
DEBUG:aioopenssl.trace.fd=14:clearing readers/writers
ERROR:asyncio:Exception in callback <bound method STARTTLSTransport._tls_do_handshake of <aioopenssl.STARTTLSTransport object at 0x10ebab748>>
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/Users/tikhonov_a/.pyenv/versions/aiofcm/lib/python3.7/site-packages/aioopenssl/__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "/Users/tikhonov_a/.pyenv/versions/aiofcm/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/tikhonov_a/.pyenv/versions/aiofcm/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/Users/tikhonov_a/.pyenv/versions/aiofcm/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
```

**Comment by horazont** [comment]
This is at least weird. I don’t think there should ever be a case where PyOpenSSL and openssl have different meanings on a certificates validity.

Thanks for the info, I’ll have to look into it, although with the present information, I think it’s unlikely that aioxmpp itself is at fault. Please consider checking your environment for any SSL configuration oddities.

**Comment by spice0xff** [comment]
> can you please try, in your shell:
> 
> ```shell
> openssl s_client -connect FCM_SERVER_URL:FCM_SERVER_PORT < /dev/null | grep -i verif
> ```
> 
> (of course with the proper replacements for the variables above) and paste the output?

```
$ openssl s_client -connect fcm-xmpp.googleapis.com:5235 < /dev/null | grep -i verif
    Verify return code: 0 (ok)
depth=2 OU = GlobalSign Root CA - R2, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = US, O = Google Trust Services, CN = Google Internet Authority G3
verify return:1
depth=0 C = US, ST = California, L = Mountain View, O = Google LLC, CN = *.googleapis.com
verify return:1
read:errno=0
```

**Comment by horazont** [comment]
Okay, this is very weird.

The logs you give indicate that OpenSSL is telling us that the certificate is not valid right away; this is nothing aioxmpp does. When I use s_client against ``fcm-xmpp.googleapis.com:5235`` myself, I get a certificate which is definitely trusted by my OpenSSL.

I tried to reproduce the problem by modifying the ``quickstart_echo_bot.py`` script to connect to FCM using your override peer seetings, and the SSL parts seem to work without any issue.

I suspect that your OpenSSL setup is broken in some way. Note that I’m not sure that PyOpenSSL supports LibreSSL in any way, so you might be looking at the wrong place when you check LibreSSL configuration.

**Comment by horazont** [comment]
Ah, I just saw the issue you linked. You can tell aioxmpp that you want to construct your own OpenSSL context by adpating the security layer constructed by make_security_layer (see also #283). You can do this like that:

```python
def my_fancy_factory():
    ctx = aioxmpp.security_layer.default_ssl_context()
    # ctx is a PyOpenSSL.SSL.Context, do whatever you need to do to it
    # NOTE: it is not recommended to create a plain PyOpenSSL.SSL.Context and go
    # from there!
    # aioxmpp.security_layer.default_ssl_context does some sane things (like 
    # enabling verification)
    return ctx

aioxmpp.Client(
    ...,
    aioxmpp.make_security_layer(...)._replace(
        ssl_context_factory=my_fancy_factory,
    ),
    ...
)
```

**Comment by spice0xff** [comment]
Thanks for you answer!
I change my code to:
```
def my_fancy_factory():
    ctx = aioxmpp.security_layer.default_ssl_context()
    # ctx is a PyOpenSSL.SSL.Context, do whatever you need to do to it
    # NOTE: it is not recommended to create a plain PyOpenSSL.SSL.Context and go
    # from there!
    # aioxmpp.security_layer.default_ssl_context does some sane things (like
    # enabling verification)
    return ctx


async def main(jid, password, recipient):
    aioxmpp.stanza.Message.fcm_payload = aioxmpp.xso.Child([FCMPayload])

    aioxmpp.node.PresenceManagedClient.security_layer=aioxmpp.make_security_layer(FCM_API_KEY)._replace(
        ssl_context_factory=my_fancy_factory,
    ),

    client = aioxmpp.node.PresenceManagedClient(
        aioxmpp.structs.JID.fromstr(jid),
        aioxmpp.security_layer.tls_with_password_based_authentication(password),
        override_peer=[(FCM_SERVER_URL, FCM_SERVER_PORT, aioxmpp.connector.XMPPOverTLSConnector())],
    )

    payload = FCMPayload()
    payload.text = json.dumps({
        "message_id": str(uuid.uuid4()),
        "to": recipient,
        "data": {
            "test": "test"
        }
    })

    async with aioxmpp.node.UseConnected(client, timeout=datetime.timedelta(seconds=30)) as stream:
        msg = aioxmpp.stanza.Message(type_="normal", id_="")
        msg.fcm_payload = payload
        await stream.send_and_wait_for_sent(msg)


asyncio.get_event_loop().run_until_complete(main(FCM_JID, FCM_API_KEY, RECIPIENT))
```
but it had no effect.

Maybe i not understand your idea or made a mistake in the implementation?
Maybe i need to deploy a docker container to reproduce this problem?

**Comment by horazont** [comment]
Sorry, I was being unclear. I was giving a suggestion how to deal with [the comment given by the PyOpenSSL folks](https://github.com/pyca/pyopenssl/issues/823#issuecomment-468675241).

@reaperhulk suggested to call load_verify_locations on the context; the ``my_fancy_factory`` function I proposed above is the way to do that, but you’ll have to fill in the blanks yourself since I can’t test this case anyways :)

**Comment by spice0xff** [comment]
I have reproduced this problem in docker image. This can be run:
docker run -it spice0xff/aioxmpp_test python ~/aioxmpp_test/aioxmpp_test.py
Can you try this?

**Comment by tungd** [comment]
I run into this issue today, turns out aioxmpp already have support for this, you'll need to use `aioxmpp.security_layer.make(..., no_verify=True)`. Replacing `ssl_context_factory` isn't enough, the verify flag of the SSLContext is actually controlled by `certificate_verifier_factory`. You can read the doc of `security_layer` for information why it's needed.

**Comment by horazont** [comment]
> I run into this issue today, turns out aioxmpp already have support for this, you'll need to use `aioxmpp.security_layer.make(..., no_verify=True)`. Replacing `ssl_context_factory` isn't enough, the verify flag of the SSLContext is actually controlled by `certificate_verifier_factory`. You can read the doc of `security_layer` for information why it's needed.

Yeah, but you should never ever set ``no_verify=True`` outside of trusted networks.

**Comment by C0D3D3V** [comment]
@spice0xff 
Because I just had the same problem I just wanted to clarify here how the function must look like, if someone is looking for it...
```
def my_fancy_factory():
        ctx = aioxmpp.security_layer.default_ssl_context()
        ctx.load_verify_locations(certifi.where())
        return ctx
```
