### ISSUE TITLE
XEP-0198: requires port in connection location despite this being explicitly optional in the XEP

### ISSUE THREAD

**Issue by Terbau** [horazont/aioxmpp#290]
Hey. Im pretty new to aioxmpp and xmpp in general. Im attempting to connect to epicgames xmpp service with the following code (just testing for now):
```py
async def connect_xmpp(loop, token, id):
    jid = aioxmpp.JID.fromstr(f"{id}@prod.ol.epicgames.com")

    client = aioxmpp.PresenceManagedClient(
        jid,
        aioxmpp.make_security_layer(token, no_verify=True),
        override_peer=[("xmpp-service-prod.ol.epicgames.com", 5222, aioxmpp.connector.STARTTLSConnector())]
    )

    def message_received(msg):
        print(msg.body)

    message_dispatcher = client.summon(
        aioxmpp.dispatcher.SimpleMessageDispatcher
    )

    message_dispatcher.register_callback(
        None,
        None,
        message_received,
    )

    def available_presence_received(pres):
        print(pres.status)
        pass

    presence_dispatcher = client.summon(
        aioxmpp.dispatcher.SimplePresenceDispatcher,
    )

    presence_dispatcher.register_callback(
        None,
        None,
        available_presence_received,
    )

    async with client.connected() as stream:
        while True:
            await asyncio.sleep(1)
```
However, on startup I receive this error:
```py
unexpected exception while parsing stanza bubbled up through parser. stream so ded.
Traceback (most recent call last):
  File "C:\Users\brage\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aioxmpp\protocol.py", line 592, in _rx_feed
    self._parser.feed(blob)
  File "C:\Users\brage\AppData\Local\Programs\Python\Python37-32\lib\xml\sax\expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "c:\_work\5\s\modules\pyexpat.c", line 471, in EndElement
  File "C:\Users\brage\AppData\Local\Programs\Python\Python37-32\lib\xml\sax\expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "C:\Users\brage\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aioxmpp\xml.py", line 1028, in endElementNS
    self._end_element_exception_handling()
  File "C:\Users\brage\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aioxmpp\xml.py", line 1005, in _end_element_exception_handling
    self.on_exception(exc)
  File "C:\Users\brage\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aioxmpp\protocol.py", line 559, in _rx_exception
    raise exc from context
  File "C:\Users\brage\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aioxmpp\xml.py", line 933, in startElementNS
    self._driver.startElementNS(name, qname, attributes)
  File "C:\Users\brage\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aioxmpp\xso\model.py", line 2375, in startElementNS
    self._send(("start", uri, localname, dict(attributes)))
  File "C:\Users\brage\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aioxmpp\xso\model.py", line 2364, in _send
    self._dest.send(value)
  File "C:\Users\brage\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aioxmpp\xso\model.py", line 2515, in __call__
    cb((yield from cls.parse_events(ev_args, self._ctx)))
  File "C:\Users\brage\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aioxmpp\xso\model.py", line 1858, in parse_events
    if not prop.from_value(obj, value):
  File "C:\Users\brage\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aioxmpp\xso\model.py", line 409, in from_value
    parsed = self.type_.parse(value)
  File "C:\Users\brage\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aioxmpp\xso\types.py", line 608, in parse
    raise ValueError("missing colon in connection location")
ValueError: missing colon in connection location
```

This is the string its failing to parse: `xmpp-service-prod06-blue-i-0c46f245d76fee7c6.ol.epicgames.net`.

Since I don't have that much experience I've tried to change a couple of lines in the aioxmpp library just to see if a connection would be established without this error (I know this is a bad idea, thats why im asking for help.). 

I changed [these lines](https://github.com/horazont/aioxmpp/blob/6c8eeda7f02220ec9415eeebc0b1712da0cfe766/aioxmpp/xso/types.py#L603-L608) to the lines below and then it works and a connection successfully gets established.
```py
def parse(self, v): 
        # v = v.strip()
        # addr, _, port = v.rpartition(":")      
        # if not _:
        #     raise ValueError("missing colon in connection location")
        # port = int(port)
        
        # TESTING
        addr = v
        port = 5222
```

Again, I'm asking for help because I want to avoid changing the library's code. Thanks.

**Comment by horazont** [comment]
This is a bug in aioxmpp, well spotted.

When implementing this feature, I missed the emphasized part from [XEP-0198](https://xmpp.org/extensions/xep-0198.html#enable):

> The <enabled/> element MAY include a 'location' attribute to specify the server's preferred IP address or hostname (**optionally** with a port) for reconnection, in the form specified in Section 4.9.3.19 of RFC 6120 (i.e., "domainpart:port", where IPv6 addresses are enclosed in square brackets "[...]" as described in RFC 5952 [6])

Thanks for the report.

**Comment by Terbau** [comment]
Hey. I was just wondering when you estimate a fix for this will roll out? I'm almost ready to release my project and was just wondering how long I might expect to wait.

**Comment by horazont** [comment]
@Terbau I see; I can push out a patch release tomorrow night (UTC+2) if it’s that urgent.

**Comment by Terbau** [comment]
I would really appreciate that. Thanks! :)

**Comment by horazont** [comment]
Waiting for CI to turn green for the release: https://travis-ci.org/horazont/aioxmpp/builds/555858230

**Comment by horazont** [comment]
@Terbau 0.10.4 released, could you test and report back whether your issue is fixed?

**Comment by Terbau** [comment]
Can confirm the issue has been resolved. Thanks :)
