### ISSUE TITLE
tests.test_protocol.TestXMLStream fails for python 3.5.0

### ISSUE THREAD

**Issue by rku** [horazont/aioxmpp#3]
With python 3.5.0, the test `tests.test_protocol.TestXMLStream` fails on my system with the following error message:

```
ERROR: test_unknown_top_level_produces_stream_error (tests.test_protocol.TestXMLStream)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rene/repos/aioxmpp/tests/test_protocol.py", line 393, in test_unknown_top_level_produces_stream_error
    TransportMock.Close()
  File "/home/rene/repos/aioxmpp/aioxmpp/testutils.py", line 38, in run_coroutine
    timeout=timeout))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 342, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 378, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/home/rene/repos/aioxmpp/aioxmpp/testutils.py", line 364, in run_test
    yield from self._write_eof(*args)
RuntimeError: generator raised StopIteration
-------------------- >> begin captured logging << --------------------
aioxmpp.XMLStream: DEBUG: SENT b'<?xml version="1.0"?><stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" to="bar.example" version="1.0">'
aioxmpp.XMLStream: DEBUG: RECV b'<stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="bar.example" to="foo@bar.example" id="abc" version="1.0">'
aioxmpp.XMLStream: DEBUG: RECV b'<foo xmlns="uri:bar"/>'
aioxmpp.XMLStream: DEBUG: SENT b'<stream:error><text xmlns="urn:ietf:params:xml:ns:xmpp-streams">unsupported stanza: {uri:bar}foo</text><unsupported-stanza-type xmlns="urn:ietf:params:xml:ns:xmpp-streams"/></stream:error>'
aioxmpp.XMLStream: DEBUG: SENT b'</stream:stream>'
aioxmpp.XMLStream: DEBUG: waiting for at most 15 seconds for peer stream footer
aioxmpp.XMLStream: DEBUG: RECV b'</stream:stream>'
--------------------- >> end captured logging << ---------------------
```

**Comment by rku** [comment]
This has been fixed in devel.
