### ISSUE TITLE
certificate verification failed (by OpenSSL) Error!

### ISSUE THREAD

**Issue by habou98** [horazont/aioxmpp#323]
Hello,
this is my code:
import aioxmpp as xmpp;
import asyncio

async def some_function():
    jid = xmpp.JID.fromstr("my jid")
    password = "my password"
    client = xmpp.PresenceManagedClient(jid, xmpp.make_security_layer(password))
    async with client.connected():
        ...
    msg = xmpp.Message(to=xmpp.JID.fromstr("my jid"), type_=xmpp.MessageType.CHAT,)
    msg.body[None] = "Hello!"
    await client.send(msg)

asyncio.run(some_function())

Error message:

certificate verification failed (by OpenSSL)
Fatal error on tls handshake
protocol: <aioxmpp.protocol.XMLStream object at 0x0000011D9939C748>
transport: <aioopenssl.STARTTLSTransport object at 0x0000011D9938A188>
Traceback (most recent call last):
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioopenssl\__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioopenssl\__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AGA-05\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioopenssl\__init__.py", line 346, in _tls_do_handshake
    self._waiter.set_exception(exc)
asyncio.base_futures.InvalidStateError: invalid state
connection failed: _force_close() called
certificate verification failed (by OpenSSL)
Fatal error on tls handshake
protocol: <aioxmpp.protocol.XMLStream object at 0x0000011D99455408>
transport: <aioopenssl.STARTTLSTransport object at 0x0000011D99455688>
Traceback (most recent call last):
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioopenssl\__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioopenssl\__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AGA-05\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioopenssl\__init__.py", line 346, in _tls_do_handshake
    self._waiter.set_exception(exc)
asyncio.base_futures.InvalidStateError: invalid state
connection failed: _force_close() called
certificate verification failed (by OpenSSL)
Fatal error on tls handshake
protocol: <aioxmpp.protocol.XMLStream object at 0x0000011D99455F08>
transport: <aioopenssl.STARTTLSTransport object at 0x0000011D993E91C8>
Traceback (most recent call last):
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioopenssl\__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioopenssl\__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AGA-05\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioopenssl\__init__.py", line 346, in _tls_do_handshake
    self._waiter.set_exception(exc)
asyncio.base_futures.InvalidStateError: invalid state
connection failed: _force_close() called
certificate verification failed (by OpenSSL)
Fatal error on tls handshake
protocol: <aioxmpp.protocol.XMLStream object at 0x0000011D99462EC8>
transport: <aioopenssl.STARTTLSTransport object at 0x0000011D99455B08>
Traceback (most recent call last):
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioopenssl\__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioopenssl\__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AGA-05\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioopenssl\__init__.py", line 346, in _tls_do_handshake
    self._waiter.set_exception(exc)
asyncio.base_futures.InvalidStateError: invalid state
connection failed: _force_close() called
out of connection attempts
main failed
Traceback (most recent call last):
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioxmpp\node.py", line 824, in _on_main_done
    task.result()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioxmpp\node.py", line 989, in _main
    yield from self._main_impl()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioxmpp\node.py", line 951, in _main_impl
    logger=self.logger)
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioxmpp\node.py", line 416, in connect_xmlstream
    exceptions
aioxmpp.errors.MultiOSError: failed to connect to XMPP domain 'xchat.baga.ma': multiple errors: _force_close() called
Traceback (most recent call last):
  File "C:/Users/AGA-05/PycharmProjects/xmpp_test/test.py", line 17, in <module>
    asyncio.run(some_function())
  File "C:\Users\AGA-05\AppData\Local\Programs\Python\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\AGA-05\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "C:/Users/AGA-05/PycharmProjects/xmpp_test/test.py", line 10, in some_function
    async with client.connected():
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioxmpp\node.py", line 1630, in __aenter__
    yield from conn_future
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioxmpp\node.py", line 824, in _on_main_done
    task.result()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioxmpp\node.py", line 989, in _main
    yield from self._main_impl()
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioxmpp\node.py", line 951, in _main_impl
    logger=self.logger)
  File "C:\Users\AGA-05\PycharmProjects\xmpp_test\venv\lib\site-packages\aioxmpp\node.py", line 416, in connect_xmlstream
    exceptions
aioxmpp.errors.MultiOSError: failed to connect to XMPP domain 'xchat.baga.ma': multiple errors: _force_close() called

![Capture](https://user-images.githubusercontent.com/60615357/74452193-05023580-4e81-11ea-9c3d-16d319597bd1.PNG)

**Comment by horazont** [comment]
This seems to be run on windows. Which asyncio event loop type are you using?

Also, if certificate verification fails that’s a problem between the server and your local trust store. I think on Windows, [PyOpenSSL does not have a default store](https://github.com/pyca/pyopenssl/issues/823#issuecomment-468675241). So you have to load one yourself, like I described [in this other comment](https://github.com/horazont/aioxmpp/issues/282#issuecomment-468699755).
