### ISSUE TITLE
certificate hostname mismatch (doesn’t match for '127.0.0.1')

### ISSUE THREAD

**Issue by pastoreerrante** [horazont/aioxmpp#324]
I am not able to perform a successful tls handshake with my xmpp server.

Error: 
```python
certificate hostname mismatch (doesn’t match for '127.0.0.1')
Fatal error on tls handshake
protocol: <aioxmpp.protocol.XMLStream object at 0x7f5877dde400>
transport: <aioopenssl.STARTTLSTransport object at 0x7f587c28cbe0>
Traceback (most recent call last):
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioopenssl/__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioopenssl/__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/daniele/.pyenv/versions/3.7.0/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioopenssl/__init__.py", line 346, in _tls_do_handshake
    self._waiter.set_exception(exc)
asyncio.base_futures.InvalidStateError: invalid state
connection failed: _force_close() called
connection failed: [Errno 111] Connect call failed ('127.0.0.1', 5222)
certificate hostname mismatch (doesn’t match for '127.0.0.1')
Fatal error on tls handshake
protocol: <aioxmpp.protocol.XMLStream object at 0x7f5876b4c320>
transport: <aioopenssl.STARTTLSTransport object at 0x7f5877ddee10>
Traceback (most recent call last):
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioopenssl/__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioopenssl/__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/daniele/.pyenv/versions/3.7.0/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioopenssl/__init__.py", line 346, in _tls_do_handshake
    self._waiter.set_exception(exc)
asyncio.base_futures.InvalidStateError: invalid state
connection failed: _force_close() called
connection failed: [Errno 111] Connect call failed ('127.0.0.1', 5222)
certificate hostname mismatch (doesn’t match for '127.0.0.1')
Fatal error on tls handshake
protocol: <aioxmpp.protocol.XMLStream object at 0x7f5874adb128>
transport: <aioopenssl.STARTTLSTransport object at 0x7f5874adb2e8>
Traceback (most recent call last):
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioopenssl/__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioopenssl/__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/daniele/.pyenv/versions/3.7.0/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioopenssl/__init__.py", line 346, in _tls_do_handshake
    self._waiter.set_exception(exc)
asyncio.base_futures.InvalidStateError: invalid state
connection failed: _force_close() called
connection failed: [Errno 111] Connect call failed ('127.0.0.1', 5222)
certificate hostname mismatch (doesn’t match for '127.0.0.1')
Fatal error on tls handshake
protocol: <aioxmpp.protocol.XMLStream object at 0x7f5874adbe10>
transport: <aioopenssl.STARTTLSTransport object at 0x7f5874ae3048>
Traceback (most recent call last):
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioopenssl/__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioopenssl/__init__.py", line 331, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/daniele/.pyenv/versions/3.7.0/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioopenssl/__init__.py", line 346, in _tls_do_handshake
    self._waiter.set_exception(exc)
asyncio.base_futures.InvalidStateError: invalid state
connection failed: _force_close() called
connection failed: [Errno 111] Connect call failed ('127.0.0.1', 5222)
out of connection attempts
main failed
Traceback (most recent call last):
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioxmpp/node.py", line 824, in _on_main_done
    task.result()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioxmpp/node.py", line 989, in _main
    yield from self._main_impl()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioxmpp/node.py", line 951, in _main_impl
    logger=self.logger)
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioxmpp/node.py", line 416, in connect_xmlstream
    exceptions
aioxmpp.errors.MultiOSError: failed to connect to XMPP domain '127.0.0.1': multiple errors: _force_close() called, [Errno 111] Connect call failed ('127.0.0.1', 5222)
Traceback (most recent call last):
  File "pubsub2.py", line 65, in <module>
    loop.run_until_complete(forever())
  File "/home/daniele/.pyenv/versions/3.7.0/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "pubsub2.py", line 47, in forever
    async with client.connected() as stream:
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioxmpp/node.py", line 1630, in __aenter__
    yield from conn_future
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioxmpp/node.py", line 824, in _on_main_done
    task.result()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioxmpp/node.py", line 989, in _main
    yield from self._main_impl()
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioxmpp/node.py", line 951, in _main_impl
    logger=self.logger)
  File "/home/daniele/prj/ea/xmpp/venv/lib/python3.7/site-packages/aioxmpp/node.py", line 416, in connect_xmlstream
    exceptions
aioxmpp.errors.MultiOSError: failed to connect to XMPP domain '127.0.0.1': multiple errors: _force_close() called, [Errno 111] Connect call failed ('127.0.0.1', 5222)
Future exception was never retrieved
future: <Future finished exception=ConnectionError('stream shut down')>
ConnectionError: stream shut down
Future exception was never retrieved
future: <Future finished exception=ConnectionError('stream shut down')>
ConnectionError: stream shut down
Future exception was never retrieved
future: <Future finished exception=ConnectionError('stream shut down')>
ConnectionError: stream shut down
Future exception was never retrieved
future: <Future finished exception=ConnectionError('stream shut down')>
ConnectionError: stream shut down

```

OpenSSL is clearly not able to verify my server certificate ('certificate verify failed') and I think the problem arises from the fact that aioxmpp is passing 127.0.0.1 as server common name to Openssl.

This obviously fails since my server common name is: mitlcsm.milano.ea.it.

The relevant portion of my code:
```python
    # set up the client object
    jid = aioxmpp.JID.fromstr("scmadministrator@127.0.0.1", strict=True)
    password = "somepsw"

    client = aioxmpp.PresenceManagedClient(
        jid,
        # aioxmpp.make_security_layer(password, no_verify=True,),
        aioxmpp.make_security_layer(password),
        override_peer=[
            ("mitlcsm.milano.ea.it", 5222, aioxmpp.connector.STARTTLSConnector())
        ],
    )
```
So I think aioxmpp is using my jid domain (127.0.0.1) instead of "mitlcsm.milano.ea.it" (specified in override_peer list) as a common name for cert validation.

Finally, I did check with plain openssl and the full certificate chain seems trusted:

```bash
openssl s_client -connect mitlcsm.milano.ea.it:5222 -starttls xmpp | grep verify
depth=2 DC = it, DC = ea, DC = milano, CN = milano-MIROOTCA01-CA
verify return:1
depth=1 DC = it, DC = ea, DC = milano, CN = EURA-CA
verify return:1
depth=0 C = IT, ST = Italia, L = Milano, O = EUROPASSISTANCE, OU = UCCE, CN = MITLCSM.milano.ea.it
verify return:1
```
Is there a way to overcome this issue? 

Thanks

**Comment by horazont** [comment]
This is working as intended. In XMPP, TLS certificates need to have the domain of the JID as commonName or subjectAltName.

There are exceptions (for example, if the SRV delegation is DNSSEC-signed), but those neither apply to your case nor are they implemented in aioxmpp.

In your very specific case where all connection attempts which can ever succeed happen via override_peers, aioxmpp *could* also accept the name given in there. However, this is (a) not implemented and (b) more tricky than it sounds, since the same list is internally also used for potentially untrusted peers which we *do* need to validate against the domain part of the JID.

You could try certificate/public key pinning, but it is underdocumented and I don't know off the top of my head if that skips the name check (although it should). I'm on mobile, so I can't check.

Note that all of these are hacks. The correct way to fix your issue is to make your XMPP deployment standards-compliant so that the connection procedure from RFC 6120 can succeed. That means using a proper hostname in the domainpart and obtaining a matching TLS certificate for it.

--
Jonas Schäfer
This was sent from mobile, and I'm not good with those. Sorry for brevity and such.

17 Feb 2020 11:51:45 am Daniele <notifications@github.com>:

**Comment by horazont** [comment]
Let’s expand on this. Basically, your options are:

- Fix the deployment (preferred)
- Use Certificate / Public key pinning: This allows to ignore the hostname check, but the format of the built-in pin stores is currently underdocumented. An example of a working pin store can be found in the aioxmpp end-to-end tests though:

  - example [pinstore.json](https://github.com/horazont/aioxmpp/blob/devel/.travis-pinstore.json)
  - tool to generate an pinstore entry from a certificate: [cert_to_pk_pin.py](https://github.com/horazont/aioxmpp/blob/devel/utils/cert_to_pk_pin.py)
  - with a proper pinstore.json, you should be able to use it in ``make_security_layer`` like this:

    ```python
    with open("pinstore.json", "r") as f:
        pinstore = json.load(f)
    … = ….Client(…, make_security_layer(…, pin_store=pinstore, pin_type=aioxmpp.security_layer.PinType.PUBLIC_KEY)
    ```

  The downside is that you’ll have to update the pin store whenever the key(!) of your certificate changes.

- Write your own certificate verifier. This is a tricky business and I most certainly do not recommend you to do that, so I won’t go into details here. Even turning of TLS is probably a good idea, because then you know *for sure* that things are screwed up, instead of assuming that everything is OK because of your custom verifier.

- Turn of TLS verification altogether (very bad idea unless this is purely localhost).

**Comment by pastoreerrante** [comment]
Thank you for the detailed explanation.

**Comment by horazont** [comment]
@pastoreerrante If there’s any more you need, let me know.
