### ISSUE TITLE
Catch connection end exceptions

### ISSUE THREAD

**Issue by azmeuk** [horazont/aioxmpp#33]
Related to #16. Tested with aioxmpp 0.7.0 and python 3.5.

Google's Firebase Cloud Messaging server do not bother to properly close the TLS connection once the TCP stream is closed. This generates tracebacks such [as this one](https://gist.github.com/azmeuk/227b8e8f6adf92e08a6ffc2425310d0a). 
```python
Traceback (most recent call last):
  File "local.virtualenv/lib/python3.5/site-packages/aioopenssl/__init__.py", line 446, in _read_ready
    data = self._sock.recv(self.MAX_SIZE)
  File "local.virtualenv/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1321, in recv
    self._raise_ssl_error(self._ssl, result)
  File "local.virtualenv/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1184, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')
```
Since it is an expected behavior, it would be great to have a way to catch the exception, to silence it.

**Comment by horazont** [comment]
This is in fact an aioopenssl issue and I’m closing it here. See horazont/aioopenssl#2.
