### ISSUE TITLE
Unable to register listener with Python3.9

### ISSUE THREAD

**Issue by pszafer** [horazont/aioxmpp#352]
Hi,
thanks for this lib!

With python 3.9 I have following error:
```
Traceback (most recent call last):
  File "/DIR//venv/lib/python3.9/site-packages/aioxmpp/stream.py", line 1998, in _run
    with (yield from self._broker_lock):
TypeError: 'Lock' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/DIR//venv/lib/python3.9/site-packages/aioxmpp/stream.py", line 889, in _done_handler
    task.result()
  File "/DIR//venv/lib/python3.9/site-packages/aioxmpp/stream.py", line 2029, in _run
    with (yield from self._broker_lock):
TypeError: 'Lock' object is not iterable
```

Do you have plans to release new version with some fixes for py3.9 soon?

**Comment by horazont** [comment]
Hi!

This is already fixed in current develop, but I need to make a release. I’ll see to make that happen soon.

Thanks for the reminder!

**Comment by horazont** [comment]
You can follow #354 for starters. When that’s done, I intend to release 0.12 ASAP.

**Comment by pszafer** [comment]
thanks!

**Comment by horazont** [comment]
@pszafer I just pushed 0.12.0 to PyPI, have fun! Debian packages are on the way, too.
