### ISSUE TITLE
SSL Certificate Verify failed

### ISSUE THREAD

**Issue by Bdoom** [horazont/aioxmpp#379]
Is there a way to skip ssl cert validation? I'm using a self-signed certificate while in development. 

```D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\Scripts\python.exe D:/repos/Perforce/orange_project/UGH_Tools/Koala/main.py
certificate verification failed (by OpenSSL)
Fatal error on tls handshake
protocol: <aioxmpp.protocol.XMLStream object at 0x000002749AF4F970>
transport: <aioopenssl.STARTTLSTransport object at 0x000002749A280940>
Traceback (most recent call last):
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioopenssl\__init__.py", line 355, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1894, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1632, in _raise_ssl_error
    _raise_current_error()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioopenssl\__init__.py", line 355, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1894, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1632, in _raise_ssl_error
    _raise_current_error()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pbssu\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioopenssl\__init__.py", line 370, in _tls_do_handshake
    self._waiter.set_exception(exc)
asyncio.exceptions.InvalidStateError: invalid state
certificate verification failed (by OpenSSL)
Fatal error on tls handshake
protocol: <aioxmpp.protocol.XMLStream object at 0x000002749AF90AF0>
transport: <aioopenssl.STARTTLSTransport object at 0x000002749AF79480>
Traceback (most recent call last):
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioopenssl\__init__.py", line 355, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1894, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1632, in _raise_ssl_error
    _raise_current_error()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioopenssl\__init__.py", line 355, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1894, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1632, in _raise_ssl_error
    _raise_current_error()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pbssu\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioopenssl\__init__.py", line 370, in _tls_do_handshake
    self._waiter.set_exception(exc)
asyncio.exceptions.InvalidStateError: invalid state
certificate verification failed (by OpenSSL)
Fatal error on tls handshake
protocol: <aioxmpp.protocol.XMLStream object at 0x000002749AF9FE20>
transport: <aioopenssl.STARTTLSTransport object at 0x000002749B056E00>
Traceback (most recent call last):
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioopenssl\__init__.py", line 355, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1894, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1632, in _raise_ssl_error
    _raise_current_error()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioopenssl\__init__.py", line 355, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1894, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1632, in _raise_ssl_error
    _raise_current_error()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pbssu\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioopenssl\__init__.py", line 370, in _tls_do_handshake
    self._waiter.set_exception(exc)
asyncio.exceptions.InvalidStateError: invalid state
certificate verification failed (by OpenSSL)
Fatal error on tls handshake
protocol: <aioxmpp.protocol.XMLStream object at 0x000002749AF90F70>
transport: <aioopenssl.STARTTLSTransport object at 0x000002749B06C6C0>
Traceback (most recent call last):
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioopenssl\__init__.py", line 355, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1894, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1632, in _raise_ssl_error
    _raise_current_error()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioopenssl\__init__.py", line 355, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1894, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1632, in _raise_ssl_error
    _raise_current_error()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pbssu\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioopenssl\__init__.py", line 370, in _tls_do_handshake
    self._waiter.set_exception(exc)
asyncio.exceptions.InvalidStateError: invalid state
out of connection attempts
main failed
Traceback (most recent call last):
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioxmpp\node.py", line 837, in _on_main_done
    task.result()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioxmpp\node.py", line 996, in _main
    await self._main_impl()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioxmpp\node.py", line 951, in _main_impl
    tls_transport, xmlstream, features = await connect_xmlstream(
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioxmpp\node.py", line 390, in connect_xmlstream
    result = await _try_options(
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioxmpp\node.py", line 241, in _try_options
    transport, xmlstream, features = await conn.connect(
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioxmpp\connector.py", line 263, in connect
    await stream.starttls(
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioxmpp\protocol.py", line 757, in starttls
    await self._transport.starttls(ssl_context, post_handshake_callback)
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioopenssl\__init__.py", line 732, in starttls
    await self._waiter
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioopenssl\__init__.py", line 355, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1894, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1632, in _raise_ssl_error
    _raise_current_error()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
Traceback (most recent call last):
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\main.py", line 35, in <module>
    loop.run_until_complete(main('david@xmpp.ughstudios.com', 'daniel@xmpp.ughstudios.com', password, 'testmsg'))
  File "C:\Users\pbssu\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\main.py", line 12, in main
    async with client.connected() as stream:
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioxmpp\node.py", line 1651, in __aenter__
    await conn_future
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioxmpp\node.py", line 837, in _on_main_done
    task.result()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioxmpp\node.py", line 996, in _main
    await self._main_impl()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioxmpp\node.py", line 951, in _main_impl
    tls_transport, xmlstream, features = await connect_xmlstream(
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioxmpp\node.py", line 390, in connect_xmlstream
    result = await _try_options(
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioxmpp\node.py", line 241, in _try_options
    transport, xmlstream, features = await conn.connect(
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioxmpp\connector.py", line 263, in connect
    await stream.starttls(
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioxmpp\protocol.py", line 757, in starttls
    await self._transport.starttls(ssl_context, post_handshake_callback)
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioopenssl\__init__.py", line 732, in starttls
    await self._waiter
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\aioopenssl\__init__.py", line 355, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1894, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\SSL.py", line 1632, in _raise_ssl_error
    _raise_current_error()
  File "D:\repos\Perforce\orange_project\UGH_Tools\Koala\venv\lib\site-packages\OpenSSL\_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

Process finished with exit code 1
```

**Comment by horazont** [comment]
Hi @Bdoom,

Check this documentation here: https://docs.zombofant.net/aioxmpp/devel/api/public/security_layer.html#aioxmpp.security_layer.make

Does that help?

Note that `no_verify` is incredibly dangerous... :)
