### ISSUE TITLE
Endless error loop after SM resume error

### ISSUE THREAD

**Issue by jahrome** [horazont/aioxmpp#382]
Hi !
After several months of smooth operation my (very simple) client code runs into and endless error loop (i suspect it is due to a change on the server side which I don't manage).

I enabled some tracing in the code and it occurs after receiving this message from the server:
`<failed xmlns='urn:xmpp:sm:3'><error type='cancel'><item-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Unknown session</text></error></failed>"
`
 
Please find below the traceback which repeats endlessly until memory exhaustion (runs on a raspberry pi): 

```
2022-10-01 20:41:22,371 [protocol] [ERROR]  unexpected exception while parsing stanza bubbled up through parser. stream so dead.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aioxmpp/xso/model.py", line 583, in validate_contents
    obj = self.__get__(instance, type(instance))
  File "/usr/local/lib/python3.9/dist-packages/aioxmpp/xso/model.py", line 339, in __get__
    raise AttributeError(
AttributeError: attribute is unset (<aioxmpp.xso.model.Child object at 0x7f8448b160> on instance of <class 'aioxmpp.nonza.SMFailed'>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aioxmpp/protocol.py", line 487, in _rx_feed
    self._parser.feed(blob)
  File "/usr/lib/python3.9/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 459, in EndElement
  File "/usr/lib/python3.9/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/usr/local/lib/python3.9/dist-packages/aioxmpp/xml.py", line 1032, in endElementNS
    self._end_element_exception_handling()
  File "/usr/local/lib/python3.9/dist-packages/aioxmpp/xml.py", line 1018, in _end_element_exception_handling
    self.on_exception(exc)
  File "/usr/local/lib/python3.9/dist-packages/aioxmpp/protocol.py", line 447, in _rx_exception
    raise exc from context
  File "/usr/local/lib/python3.9/dist-packages/aioxmpp/xml.py", line 1027, in endElementNS
    return self._driver.endElementNS(name, qname)
  File "/usr/local/lib/python3.9/dist-packages/aioxmpp/xso/model.py", line 2543, in endElementNS
    self._send(("end",))
  File "/usr/local/lib/python3.9/dist-packages/aioxmpp/xso/model.py", line 2527, in _send
    self._dest.send(value)
  File "/usr/local/lib/python3.9/dist-packages/aioxmpp/xso/model.py", line 2678, in __call__
    cb((yield from cls.parse_events(ev_args, self._ctx)))
  File "/usr/local/lib/python3.9/dist-packages/aioxmpp/xso/model.py", line 2103, in parse_events
    obj.validate()
  File "/usr/local/lib/python3.9/dist-packages/aioxmpp/xso/model.py", line 2368, in validate
    descriptor.validate_contents(self)
  File "/usr/local/lib/python3.9/dist-packages/aioxmpp/xso/model.py", line 585, in validate_contents
    raise ValueError("missing required member")
ValueError: missing required member
2022-10-01 20:42:22,577 [__init__] [ERROR]  abort() called (invalid in state _State.CLOSED, closing=True)
2022-10-01 20:42:22,579 [node] [INFO]  stopping stream
2022-10-01 20:42:22,691 [protocol] [INFO]  b"<?xml version='1.0'?><stream:stream id='c5b9c480-95e4-466a-ac6d-652145d22cf7' xmlns:stream='http://etherx.jabber.org/streams' xml:lang='en' xmlns='jabber:client' version='1.0' from='jabber.fr'><stream:features><starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'><required/></starttls></stream:features>"
2022-10-01 20:42:22,695 [protocol] [INFO]  <aioxmpp.nonza.StartTLS object at 0x7f804337c0>
2022-10-01 20:42:22,741 [protocol] [INFO]  b"<proceed xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>"
2022-10-01 20:42:22,856 [security_layer] [INFO]  verifying certificate (preverify=1)
2022-10-01 20:42:22,859 [security_layer] [INFO]  verifying certificate (preverify=1)
2022-10-01 20:42:22,861 [security_layer] [INFO]  verifying certificate (preverify=1)
2022-10-01 20:42:23,047 [protocol] [INFO]  b"<?xml version='1.0'?><stream:stream id='859c67f3-e819-4237-8675-22f197be6f0a' xmlns:stream='http://etherx.jabber.org/streams' xml:lang='en' xmlns='jabber:client' version='1.0' from='jabber.fr'><stream:features><register xmlns='http://jabber.org/features/iq-register'/><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>SCRAM-SHA-1</mechanism><mechanism>PLAIN</mechanism></mechanisms></stream:features>"
2022-10-01 20:42:23,052 [scram] [INFO]  attempting SCRAM-SHA-1 mechanism (using SCRAMHashInfo(hashfun_name='sha1', quality=1, minimum_iteration_count=4096) hashfun)
2022-10-01 20:42:23,055 [protocol] [INFO]  <aioxmpp.nonza.SASLAuth object at 0x7f40087400>
2022-10-01 20:42:23,100 [protocol] [INFO]  b"<challenge xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>cj15bzZHNDR3SU9JeU13S2NIaGd5RmRlZjlkZTBmLWYyOTUtNDk2Zi1hYWI1LTJhYTIwYjY0OWQ3ZCxzPU5UTXdPV1UyT0dJdE56ZzNaQzAwTW1JMUxUa3pNMlV0Tnpnek1ETmhZbUV3TnpSayxpPTQwOTY=</challenge>"
2022-10-01 20:42:23,117 [protocol] [INFO]  <aioxmpp.nonza.SASLResponse object at 0x7f400872e0>
2022-10-01 20:42:23,175 [protocol] [INFO]  b"<success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>dj1vY1NHZXRqNXM1ZnRTTkcyRWN3KzhvRFNOTGs9</success>"
2022-10-01 20:42:23,239 [protocol] [INFO]  b"<?xml version='1.0'?><stream:stream id='4eaa1aa6-1c11-4de3-bd6f-9f9146dae63f' xmlns:stream='http://etherx.jabber.org/streams' xml:lang='en' xmlns='jabber:client' version='1.0' from='jabber.fr'><stream:features><c hash='sha-1' xmlns='http://jabber.org/protocol/caps' node='http://prosody.im' ver='bPUCZvJ0B8Mtg2Mwrf7VVIUqabw='/><csi xmlns='urn:xmpp:csi:0'/><sub xmlns='urn:xmpp:features:pre-approval'/><sm xmlns='urn:xmpp:sm:2'><optional/></sm><sm xmlns='urn:xmpp:sm:3'><optional/></sm><ver xmlns='urn:xmpp:features:rosterver'/><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><required/></bind><session xmlns='urn:ietf:params:xml:ns:xmpp-session'><optional/></session></stream:features>"
2022-10-01 20:42:23,246 [protocol] [INFO]  <aioxmpp.nonza.SMResume counter=24 previd='U2rXiCdBLY9Q' at 0x7f400dbf10>
2022-10-01 20:42:23,291 [protocol] [INFO]  b"<failed xmlns='urn:xmpp:sm:3'><error type='cancel'><item-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Unknown session</text></error></failed>"
2022-10-01 20:42:23,293 [protocol] [ERROR]  unexpected exception while parsing stanza bubbled up through parser. stream so dead.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aioxmpp/xso/model.py", line 583, in validate_contents
    obj = self.__get__(instance, type(instance))
  File "/usr/local/lib/python3.9/dist-packages/
```

Thanks

**Comment by horazont** [comment]
@jahrome Thanks for the detailed issue report! This is definitely some kind of bug in aioxmpp. I'll look into it later today or tomorrow.

**Comment by horazont** [comment]
@jahrome Aside from a bug in aioxmpp, this is also a bug in the server. It sends:

```
<failed xmlns='urn:xmpp:sm:3'>
  <error type='cancel'>
    <item-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
    <text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Unknown session</text>
  </error>
</failed>
```

But [XEP-0198 specifies that the error condition (in this case `<item-not-found/>`) is a direct child of the `<failed/>` element, not wrapped in `<error/>`](https://xmpp.org/extensions/xep-0198.html#errors). So if you could report that issue upstream at the server (or let me know which server implementation this is), that would be great.

That aside, aioxmpp should handle malformed stanzas more gracefully during SM handshaking, so I'll look into increasing the resilience there.

Would you be able to apply and test patches if I provide them?

**Comment by jahrome** [comment]
Thanks @horazont a lot for the quick response. I believe the server is Prosody as seen in some xml:
`<stream:features><c hash='sha-1' xmlns='http://jabber.org/protocol/caps' node='http://prosody.im' ver='bPUCZvJ0B8Mtg2Mwrf7VVIUqabw='/>`

I'll be glad to test patches for sure !

**Comment by horazont** [comment]
On 2 October 2022 18:04:57 UTC, Jerome Marty ***@***.***> wrote:
>Thanks @horazont a lot for the quick response. I believe the server is Prosody as seen in some xml:
>`<stream:features><c hash='sha-1' xmlns='http://jabber.org/protocol/caps' node='http://prosody.im' ver='bPUCZvJ0B8Mtg2Mwrf7VVIUqabw='/>`
>
>I'll be glad to test patches for sure !
>

Ah well spotted.

I brought this report upstream to prosody already and will look into a fix to improve resilience in aioxmpp.

**Comment by horazont** [comment]
Hi @jahrome!

Could you take a look at https://github.com/horazont/aioxmpp/pull/383 and see if that fixes the loop?

(Though I'm not sure how well-reproducible that is--a test whether it breaks anything for you would already be appreciated though.)

**Comment by horazont** [comment]
Proposed a fix against prosody: https://hg.prosody.im/contrib/rev/0dc80024fdd2
