### ISSUE TITLE
Missing pytz dependency in setup.py?

### ISSUE THREAD

**Issue by JulienPalard** [horazont/aioxmpp#389]
Tried `pip install aioxmpp`, and when trying it I got:

```
Traceback (most recent call last):
  File ".venv/bin/http-to-xmpp", line 5, in <module>
    from http_to_xmpp import main
  File ".venv/lib/python3.11/site-packages/http_to_xmpp.py", line 10, in <module>
    import aioxmpp
  File ".venv/lib/python3.11/site-packages/aioxmpp/__init__.py", line 101, in <module>
    from .errors import (  # NOQA
  File ".venv/lib/python3.11/site-packages/aioxmpp/errors.py", line 90, in <module>
    from . import xso, i18n, structs
  File ".venv/lib/python3.11/site-packages/aioxmpp/xso/__init__.py", line 588, in <module>
    from .types import (  # NOQA: F401
  File ".venv/lib/python3.11/site-packages/aioxmpp/xso/types.py", line 42, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'
```

After installing it via `pip install pytz` it works though :)

**Comment by C0D3D3V** [comment]
@horazont  I think the problem is, that you have tzlocal in your setup.py https://pypi.org/project/tzlocal/ but you actually use pytz that is no longer dep. of tzlocal.

**Comment by kousu** [comment]
I'm seeing this too. I'm probably going to keep using slixmpp until this is resolved.
