### ISSUE TITLE
Potential incompatibility with Python 3.11

### ISSUE THREAD

**Issue by delliott0000** [horazont/aioxmpp#395]
Using `aioxmpp.PresenceManagedClient.connected` in an asynchronous context manager is resulting in `NotImplementedError` being raised from within the `asyncio` standard library.

Minimal code to reproduce error:
```py
import aioxmpp
import asyncio

async def main():
    client = aioxmpp.PresenceManagedClient(
        aioxmpp.JID('username', 'domain', 'resource'),
        aioxmpp.make_security_layer('password')
    )
    async with client.connected() as stream:
        ...

asyncio.run(main())
```
Replacing `'domain'` with a valid XMPP domain.

Traceback:
```
Traceback (most recent call last):
  File "C:\Path\venv\Lib\site-packages\aioxmpp\node.py", line 837, in _on_main_done
    task.result()
  File "C:\Path\venv\Lib\site-packages\aioxmpp\node.py", line 1005, in _main
    await self._main_impl()
  File "C:\Path\venv\Lib\site-packages\aioxmpp\node.py", line 951, in _main_impl
    tls_transport, xmlstream, features = await connect_xmlstream(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Path\venv\Lib\site-packages\aioxmpp\node.py", line 390, in connect_xmlstream
    result = await _try_options(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Path\venv\Lib\site-packages\aioxmpp\node.py", line 241, in _try_options
    transport, xmlstream, features = await conn.connect(
                                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Path\venv\Lib\site-packages\aioxmpp\connector.py", line 195, in connect
    transport, _ = await ssl_transport.create_starttls_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Path\venv\Lib\site-packages\aioopenssl\__init__.py", line 894, in create_starttls_connection
    transport = STARTTLSTransport(loop, sock, protocol,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Path\venv\Lib\site-packages\aioopenssl\__init__.py", line 214, in __init__
    self._initiate_raw()
  File "C:\Path\venv\Lib\site-packages\aioopenssl\__init__.py", line 316, in _initiate_raw
    self._loop.add_reader(self._raw_fd, self._read_ready)
  File "C:\...\Python\Python311\Lib\asyncio\events.py", line 530, in add_reader
    raise NotImplementedError
NotImplementedError
Traceback (most recent call last):
  File "C:\Path\main.py", line 15, in <module>
    asyncio.run(main())
  File "C:\...\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\...\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Path\main.py", line 11, in main
    async with client.connected() as stream:
  File "C:\Path\venv\Lib\site-packages\aioxmpp\node.py", line 1660, in __aenter__
    await conn_future
  File "C:\Path\venv\Lib\site-packages\aioxmpp\node.py", line 837, in _on_main_done
    task.result()
  File "C:\Path\venv\Lib\site-packages\aioxmpp\node.py", line 1005, in _main
    await self._main_impl()
  File "C:\Path\venv\Lib\site-packages\aioxmpp\node.py", line 951, in _main_impl
    tls_transport, xmlstream, features = await connect_xmlstream(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Path\venv\Lib\site-packages\aioxmpp\node.py", line 390, in connect_xmlstream
    result = await _try_options(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Path\venv\Lib\site-packages\aioxmpp\node.py", line 241, in _try_options
    transport, xmlstream, features = await conn.connect(
                                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Path\venv\Lib\site-packages\aioxmpp\connector.py", line 195, in connect
    transport, _ = await ssl_transport.create_starttls_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Path\venv\Lib\site-packages\aioopenssl\__init__.py", line 894, in create_starttls_connection
    transport = STARTTLSTransport(loop, sock, protocol,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Path\venv\Lib\site-packages\aioopenssl\__init__.py", line 214, in __init__
    self._initiate_raw()
  File "C:\Path\venv\Lib\site-packages\aioopenssl\__init__.py", line 316, in _initiate_raw
    self._loop.add_reader(self._raw_fd, self._read_ready)
  File "C:\...\Python\Python311\Lib\asyncio\events.py", line 530, in add_reader
    raise NotImplementedError
NotImplementedError
```
Using Python `3.11.0` with `aioxmpp` version `0.13.3`.

**Comment by delliott0000** [comment]
# Update:
Being on a windows 11 machine, adding the following code before connecting fixed my issue:
```py
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

**Comment by sunmin89** [comment]
> ```python
> asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
> ```

Hi, @delliott0000 

I came across the same issue as a python newbie under Windows 10 Python 3.11.

My test code  is  the official example https://github.com/horazont/aioxmpp/blob/devel/examples/echo_bot_im.py

I don't know where should I put your line of code to this example, could you give me some suggestions , thanks!

Best!

**Comment by delliott0000** [comment]
Hi @sunmin89,

Calling `set_event_loop_policy` anywhere prior to spawning your event loop (e.g. `asyncio.run`) should work.
